/*! @mainpage bluetoe

@section intro_sec Introduction

Bluetoe is an attempt to simplify the implementation of firmware for Bluetooth Low Energy devices. Bluetooth Low Energy devices / peripherals usally implement a so called GATT Server. GATT is a protocol that alows a computer (desktop, phone etc.) to discover a devices capabilities and to interact with a device in a unified manner.

A lot of possible device capabilities are specified by the <a href="https://www.bluetooth.org">Bluetooth Special Interest Group</a>. Others capabilities are user defined and make sense only to the implemeter of a device and the used client. Those capabilities and the means how to access them are called profiles.

@section gatt_basics GATT Basics

@subsection Characteristics

The basic building blocks of GATT are characteristics. A characteristic can be thinked of as a piece of information / a variable that resides inside of a device, which clients can interact with. To identify a characteristic, an identifier, called a UUID is used. Beside some very basic properties like "readable" or "writeable", a characteristic can have additional properties like a name or structure informations (e.g. this is a structure containing 1 float followed by 2 integers).

@subsection Services

A service groups characteristics to meaningful units. A helicopter position service would for example group the X, Y, and Z position of the helicopter to a Position Service. A device can announce the implementation / existance of a service in that device, so that computers looking for a specific device can see that the device is implementing the service, without the need to connect to the device.

@subsection Profiles

A profile groups @ref Services to higher level functionality and is usually "just" a document that describes what a device must implement to be conforming to a certain profile.

@subsection UUIDs

Both, @ref Characteristics and @ref Services are identified by Universally Unique Identifiers (<a href="https://en.wikipedia.org/wiki/Universally_unique_identifier">UUID</a>). Bluetooth Low Energy basically uses two different kinds of UUIDs, one 16 bit long, the other 128 bit long.

16-bit UUIDs are exclusivly assigned by the <a href="https://www.bluetooth.org">Bluetooth Special Interest Group</a>. 128-bit UUIDs can be generated by anyone and used in custom applications that are not standardised.

16-bit UUIDs are usually notated as a 4 digit hexadecimal number. 128-bit UUIDs are grouped in packs of different size. Example: 7A5F69F4-3915-41C7-92BD-1477B35B883D.

@section start_bluetoe BlueToe's Implementation of GATT



@section Advertising
@section Binding to Hardware
@section define_gap And what's with GAP?

GAP is an other important protocol that allows a GATT client to discover devices, connect to them and to gather basic informations about a device. In Bluetooth all possible options related to GAP are passed as options to the server type definition.

@section design_goals Design Goals
*/